apiVersion: v2
name: wordpress
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
- name: wordpress
  version: 5.0.2
  repository: https://charts.helm.sh/stable
- name: mariadb
  version: 5.x.x
  repository: https://charts.helm.sh/stable
  condition: mariadb.enabled
  tags:
    - wordpress-database